# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f69298f1c1007ef538eed141b02fca82845ebce2f997d8f4ff78569bef181d3cbcd21c95bdd7c25f9715283c9b9a3ad8a4b699fc012b463f0c870b6aebd60e0

test:
  secret_key_base: 3507730c3fcbb91269251b5a9370cb418d1753101882994c6cafc8bf8070d850ba54be76ca9d8e32af7368042f8f360d0d4bc58694b92986cbaaaebc4b06c002

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
